title: DC Antiperrys
description: Sitio de guías usando Just the Docs
theme: just-the-docs

url: https://RcUchiha.github.io/dc-antiperrys

aux_links:
  Template Repository: https://github.com/RcUchiha/dc-antiperrys
